package com.romvaz.core.ui.utils

//DELAYS
const val DELAY_TIME_2000 = 2000L
const val DELAY_TIME_1000 = 1000L
const val DELAY_TIME_166 = 166L
const val DELAY_TIME_100 = 100L

//GENERAL
const val SPLASH_ANIMATION_SIZE = 8

//ANIMATIONS OFFSETS
const val SLIDE_IN_OFFSET_START = 0
const val SLIDE_IN_OFFSET_END = 1000

//MAPS
const val MAPS_ZOOM = 20f
const val DURATION_FOR_AUTO_FOCUS_MAPS = 1000
const val START_POSITION_FOR_MAP = 0.0
